'''
Use https://www.ocr2edit.com/ to convert https://twitter.com/parveenkaswan/status/1475512328267317249
'''

s = '''JGLOMGKDMSDOEOVMSCMWOQPRYTLSMLFJOMCES
KOGUKLMSMIEOPUMLSMVMGKEJSKNMLESSONSJAPQ
PEICREATIONUMXLAMFAJFLSMCGJIWLOVEPJFLAMVL
WILFEGMLEMFMEPAVBHZLSHVMUDKUITEWJTKDKNY
MSNGKDSLUGKOLSJGKLSGRATITUDEJGKLSJAKLGZV
HMCHSJWUQDLDPWSJGDSKIEMNBSKGMNBAXBOMSII
IMELNGSANVDCONNECTIONKMGEWJNNZCMANHHFL
WOIRPWIQTYIEJCZXNMXZVJSAGKSMZNVLGKELUWJK
TNSNJDORWADFXCRPWVGCRBYTNMONEYKUMLIMLY
UJVRNWCGEYVOQPOWERPUYXORWKLJDSKLGJKDSLUJI
TALIGNMENTJEVMSLUJFLSHAHMLFJELWPORIVMSMM
TGLOMGKOMSIOMCHANGEVVMSCMWOOPRYTLSMLFJ
HIMCESKOGJKLMSMIEOPUMLSMVMGKEJSKNMJAPOPE
OOMXALAMFAHEALTHJFLSMCGJIWPJFLAMVLWILFEGM
NNMFMEPAVBNZLSNVMJOKUISELFCAREVMSNGKDSL
JGKDLSIGKLSJGKLSJAKLGZVNMCNHSJWUQDLDPWSJ
GOSKIEMHBSKGMNBAXBDMSGMELNGSANVDSMGEW
JNNZCMANHHFLSTRENGTHWOIRPWIQTYIEJCZXNMR
ZVJSAGKSMZNVLGKELJWJKCNSNFAMILYJDORWADE
ACRSWVGCRBYTNKUMLIMLYBJVRNWCGEYVOXDRWS
LUDSKLWPURPOSEJKDSLUEMJGLOMGKDMSDOEOVM
STMWOQMIRACLESPRYTLSMLFJOMCESKOGJKLMSMI
ELPUMLSMVMGKEJSKNMJAPQBREAKTHROUGHPEIUM
AXLAMFAJFLSGMODTVNMWURHDKABNPOIUMAFHHAKHU
JJHJJDHJSWIIRUMAMBOGEHJAKOWHCSANKNWLALADI
'''



def return_n_groups(ipstr,n=3):

    for k,v in enumerate(ipstr):
        try:
            token = ''.join(ipstr[k:k+n])
            if test_words(token.lower()) and len(token) == n:
                yield token.lower()
        except:
            pass

def test_words(word):
    if word in WORD_LIST:
        return True
    else:
        return False

def load_words():
    '''
    download https://github.com/dwyl/english-words/blob/master/words_alpha.txt in same location
    '''
    with open('words_alpha.txt') as word_file:
        valid_words = set(word_file.read().split())

    return valid_words

def prep_n_test(s):
    for i in range(3,15):
        for t in return_n_groups(s,i):
            yield t

if __name__ == "__main__":
    WORD_LIST = load_words()
    stripped = s.strip()
    final = []
    for t in prep_n_test(stripped):
        print(t)
