s = '''JOLOMGKOMSDOE0VMSCMWOOPROTLSMLFJOMCES KOGJKLMSMIEOPJMISMVMGKEJSKNMIESSONSJAPQ PEICREATIONJMXLAMFAJFISMCGJIWLOVEPJRAMVL WILFEGMLEMFMEPAVBHZ LSNVMUDKUITEWJTKOKNV MONGIOSUGMELSJGHLSGRATITUDEJGIUSJAKLUV NMCNSJWUODLOPINSJGDSKIEMNBSKGMHBAMBONISII IMELNGSJINVOCONNECTIONKMGEWJNNUMANHFIFL NOIRPWIOTYIEJCZXNMKZUSAGIISMZHVIGKELJWJK THSNJDORWADFXCRPWVGCRBOONMONEYKUMLIMLY UJVRHWCGEVVOPOWERPUHMORWKIADSKLGJKOSI.J1 TALIGNIVIENTJEVMSLJJFLSHAHMLFJELWPORIVMSMM TGLDIVICHOMSIOMCHONGEVVMSCMWOOPROILSMIFJ IIMCESHOGJKLMSMIEOPJMISMIIIVIGHEJSKNMJAPOPE 00MRAMFAHEALTHJILSMCGJIWPJFLAMVIWILFEGM NHMFMEPAVIDIOLSNVIVIJOHUISELFCABEVMSNMSL JOHOLSJGIUSJGHLSJAHLOSIIIIMCHSJWUCIOLOPWSJ GOSKIEMNBSKGMNBAKDOMSGMELNGSANVOSMGEW JNNZCIVIANI1HFISTRENGTHWOIRPWICITYIEJCZXNMR ZVJSAGKSIVIZNVIAKELJWJHCNONFAMILYJDORWADE XCRSWVGCRBYTHKUMLIMLYBJVRNWCGEYVOXDRWS LIDSKLVOURPOSEMSLJEMJCIAMGHOMSDOEOVM STMWOOMIRACLESPRYTISMLFJOMCESKOGJKLMSMI ELPJMLSMVMGHEJOHNMJAPOBREAHTHROUGHPEIJM XLANIFAJELSGMDTVNMWURHOKABNPOIUMAFHHAKHU JJHJJOHJSWIIRUMAMBOGEHJAHOWHCSANNHLALADI'''

s1 = 'abcaretgf'

import requests

def return_n_groups(ipstr,n=3):

    for k,v in enumerate(ipstr):
        try:
            token = ''.join(ipstr[k:k+n])
            if test_words(token.lower()) and len(token) == n:
                yield token.lower()
        except:
            pass

def test_words(word):
    if word in WORD_LIST:
        return True
    else:
        return False

def load_words():
    '''
    download https://github.com/dwyl/english-words/blob/master/words_alpha.txt in same location
    '''
    with open('words_alpha.txt') as word_file:
        valid_words = set(word_file.read().split())

    return valid_words

def prep_n_test():
    for i in range(3,15):
        for t in return_n_groups(s,i):
            yield t

if __name__ == "__main__":
    WORD_LIST = load_words()
    final = []
    for t in prep_n_test():
        print(t)
