site_name: Magpie Blogs
site_url: https://ayanguha.github.io/magpie/

docs_dir: blogs # Directory where your markdown files are located

theme:
  name: material
  palette:
    # Enterprise Tech color scheme
    scheme: default
    primary: black
    accent: teal
  features:
    - content.code.copy 

nav:
  - Home: index.md
  - Applied AI Engineering:
      - "Private AI Audio Transcriber": magpie-auris.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_style: material
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list

  